name: Konnetto CI/CD - Firebase App Distribution (Debug)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    release_notes:
      type: string
      required: true
      default: 'Manual Debug Build'

jobs:
  build:
    name: Building and distributing Konnetto app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode Firebase service account
        run: echo "${{ secrets.CREDENTIAL_FILE_CONTENT }}" > firebase_service_account.json

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: firebase_service_account.json
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
